"""Language profiles for code-aware editing (issue #181).

Each ``LanguageProfile`` describes one coding language: file extensions,
indentation convention, comment syntax, bracket pairs, and a keyword set for
token classification. Profiles are pure data — no ``wx`` imports.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path


@dataclass(frozen=True, slots=True)
class LanguageProfile:
    """Describes one coding language for code-aware editing."""

    name: str
    extensions: tuple[str, ...]
    indent_unit: int = 4
    uses_tabs: bool = False
    comment_prefix: str = ""
    block_comment_start: str = ""
    block_comment_end: str = ""
    bracket_pairs: tuple[tuple[str, str], ...] = (("(", ")"), ("[", "]"), ("{", "}"))
    keywords: tuple[str, ...] = field(default_factory=tuple)


_PROFILES: tuple[LanguageProfile, ...] = (
    LanguageProfile(
        "Python",
        (".py", ".pyw", ".pyi"),
        indent_unit=4,
        comment_prefix="# ",
        keywords=(
            "False",
            "None",
            "True",
            "and",
            "as",
            "assert",
            "async",
            "await",
            "break",
            "class",
            "continue",
            "def",
            "del",
            "elif",
            "else",
            "except",
            "finally",
            "for",
            "from",
            "global",
            "if",
            "import",
            "in",
            "is",
            "lambda",
            "nonlocal",
            "not",
            "or",
            "pass",
            "raise",
            "return",
            "try",
            "while",
            "with",
            "yield",
        ),
    ),
    LanguageProfile(
        "JavaScript",
        (".js", ".mjs", ".cjs"),
        indent_unit=2,
        comment_prefix="// ",
        block_comment_start="/*",
        block_comment_end="*/",
        keywords=(
            "break",
            "case",
            "catch",
            "class",
            "const",
            "continue",
            "debugger",
            "default",
            "delete",
            "do",
            "else",
            "export",
            "extends",
            "false",
            "finally",
            "for",
            "function",
            "if",
            "import",
            "in",
            "instanceof",
            "let",
            "new",
            "null",
            "of",
            "return",
            "static",
            "super",
            "switch",
            "this",
            "throw",
            "true",
            "try",
            "typeof",
            "undefined",
            "var",
            "void",
            "while",
            "with",
            "yield",
        ),
    ),
    LanguageProfile(
        "TypeScript",
        (".ts", ".tsx", ".mts", ".cts"),
        indent_unit=2,
        comment_prefix="// ",
        block_comment_start="/*",
        block_comment_end="*/",
        keywords=(
            "abstract",
            "any",
            "as",
            "async",
            "await",
            "boolean",
            "break",
            "case",
            "catch",
            "class",
            "const",
            "constructor",
            "continue",
            "declare",
            "default",
            "delete",
            "do",
            "else",
            "enum",
            "export",
            "extends",
            "false",
            "finally",
            "for",
            "from",
            "function",
            "if",
            "implements",
            "import",
            "in",
            "instanceof",
            "interface",
            "let",
            "module",
            "namespace",
            "never",
            "new",
            "null",
            "number",
            "of",
            "override",
            "private",
            "protected",
            "public",
            "readonly",
            "return",
            "static",
            "string",
            "super",
            "switch",
            "this",
            "throw",
            "true",
            "try",
            "type",
            "typeof",
            "undefined",
            "unknown",
            "var",
            "void",
            "while",
            "with",
            "yield",
        ),
    ),
    LanguageProfile(
        "HTML",
        (".html", ".htm", ".xhtml"),
        indent_unit=2,
        block_comment_start="<!--",
        block_comment_end="-->",
        bracket_pairs=(("<", ">"), ("(", ")"), ("[", "]")),
    ),
    LanguageProfile(
        "CSS",
        (".css", ".scss", ".sass", ".less"),
        indent_unit=2,
        block_comment_start="/*",
        block_comment_end="*/",
        bracket_pairs=(("{", "}"), ("(", ")"), ("[", "]")),
    ),
    LanguageProfile(
        "YAML",
        (".yaml", ".yml"),
        indent_unit=2,
        comment_prefix="# ",
    ),
    LanguageProfile(
        "Go",
        (".go",),
        indent_unit=1,
        uses_tabs=True,
        comment_prefix="// ",
        block_comment_start="/*",
        block_comment_end="*/",
        keywords=(
            "break",
            "case",
            "chan",
            "const",
            "continue",
            "default",
            "defer",
            "else",
            "fallthrough",
            "for",
            "func",
            "go",
            "goto",
            "if",
            "import",
            "interface",
            "map",
            "package",
            "range",
            "return",
            "select",
            "struct",
            "switch",
            "type",
            "var",
        ),
    ),
    LanguageProfile(
        "C",
        (".c", ".h"),
        indent_unit=4,
        comment_prefix="// ",
        block_comment_start="/*",
        block_comment_end="*/",
        keywords=(
            "auto",
            "break",
            "case",
            "char",
            "const",
            "continue",
            "default",
            "do",
            "double",
            "else",
            "enum",
            "extern",
            "float",
            "for",
            "goto",
            "if",
            "inline",
            "int",
            "long",
            "register",
            "return",
            "short",
            "signed",
            "sizeof",
            "static",
            "struct",
            "switch",
            "typedef",
            "union",
            "unsigned",
            "void",
            "volatile",
            "while",
        ),
    ),
    LanguageProfile(
        "C++",
        (".cpp", ".cc", ".cxx", ".hpp", ".hxx"),
        indent_unit=4,
        comment_prefix="// ",
        block_comment_start="/*",
        block_comment_end="*/",
        keywords=(
            "alignas",
            "alignof",
            "and",
            "auto",
            "bool",
            "break",
            "case",
            "catch",
            "char",
            "class",
            "const",
            "constexpr",
            "continue",
            "decltype",
            "default",
            "delete",
            "do",
            "double",
            "else",
            "enum",
            "explicit",
            "export",
            "extern",
            "false",
            "float",
            "for",
            "friend",
            "goto",
            "if",
            "inline",
            "int",
            "long",
            "namespace",
            "new",
            "noexcept",
            "not",
            "nullptr",
            "operator",
            "or",
            "private",
            "protected",
            "public",
            "return",
            "short",
            "signed",
            "sizeof",
            "static",
            "struct",
            "switch",
            "template",
            "this",
            "throw",
            "true",
            "try",
            "typedef",
            "typename",
            "union",
            "unsigned",
            "using",
            "virtual",
            "void",
            "volatile",
            "while",
        ),
    ),
    LanguageProfile(
        "Rust",
        (".rs",),
        indent_unit=4,
        comment_prefix="// ",
        block_comment_start="/*",
        block_comment_end="*/",
        keywords=(
            "as",
            "async",
            "await",
            "break",
            "const",
            "continue",
            "crate",
            "dyn",
            "else",
            "enum",
            "extern",
            "false",
            "fn",
            "for",
            "if",
            "impl",
            "in",
            "let",
            "loop",
            "match",
            "mod",
            "move",
            "mut",
            "pub",
            "ref",
            "return",
            "self",
            "static",
            "struct",
            "super",
            "trait",
            "true",
            "type",
            "union",
            "unsafe",
            "use",
            "where",
            "while",
        ),
    ),
    LanguageProfile(
        "Kotlin",
        (".kt", ".kts"),
        indent_unit=4,
        comment_prefix="// ",
        block_comment_start="/*",
        block_comment_end="*/",
        keywords=(
            "abstract",
            "actual",
            "annotation",
            "as",
            "break",
            "by",
            "catch",
            "class",
            "companion",
            "const",
            "constructor",
            "continue",
            "crossinline",
            "data",
            "do",
            "dynamic",
            "else",
            "enum",
            "expect",
            "external",
            "false",
            "field",
            "file",
            "final",
            "finally",
            "for",
            "fun",
            "get",
            "if",
            "import",
            "in",
            "infix",
            "init",
            "inline",
            "inner",
            "interface",
            "internal",
            "is",
            "it",
            "lateinit",
            "noinline",
            "null",
            "object",
            "open",
            "operator",
            "out",
            "override",
            "package",
            "param",
            "private",
            "property",
            "protected",
            "public",
            "receiver",
            "reified",
            "return",
            "sealed",
            "set",
            "setparam",
            "super",
            "suspend",
            "tailrec",
            "this",
            "throw",
            "true",
            "try",
            "typealias",
            "typeof",
            "val",
            "var",
            "vararg",
            "when",
            "where",
            "while",
        ),
    ),
    LanguageProfile(
        "Shell",
        (".sh", ".bash", ".zsh", ".fish", ".ksh"),
        indent_unit=4,
        comment_prefix="# ",
        keywords=(
            "case",
            "do",
            "done",
            "elif",
            "else",
            "esac",
            "fi",
            "for",
            "function",
            "if",
            "in",
            "select",
            "then",
            "until",
            "while",
        ),
    ),
    LanguageProfile(
        "Markdown",
        (".md", ".mdx", ".markdown"),
        indent_unit=4,
        block_comment_start="<!--",
        block_comment_end="-->",
        bracket_pairs=(("[", "]"), ("(", ")"), ("<", ">")),
    ),
    LanguageProfile(
        "JSON",
        (".json", ".jsonc", ".json5"),
        indent_unit=2,
        bracket_pairs=(("{", "}"), ("[", "]")),
    ),
    LanguageProfile(
        "TOML",
        (".toml",),
        indent_unit=4,
        comment_prefix="# ",
    ),
    LanguageProfile(
        "SQL",
        (".sql",),
        indent_unit=4,
        comment_prefix="-- ",
        block_comment_start="/*",
        block_comment_end="*/",
        keywords=(
            "ADD",
            "ALL",
            "ALTER",
            "AND",
            "AS",
            "ASC",
            "BETWEEN",
            "BY",
            "CASE",
            "CHECK",
            "COLUMN",
            "CONSTRAINT",
            "CREATE",
            "CROSS",
            "DEFAULT",
            "DELETE",
            "DESC",
            "DISTINCT",
            "DROP",
            "ELSE",
            "END",
            "EXISTS",
            "FROM",
            "FULL",
            "GROUP",
            "HAVING",
            "IN",
            "INDEX",
            "INNER",
            "INSERT",
            "INTO",
            "IS",
            "JOIN",
            "LEFT",
            "LIKE",
            "LIMIT",
            "NOT",
            "NULL",
            "ON",
            "OR",
            "ORDER",
            "OUTER",
            "PRIMARY",
            "RIGHT",
            "SELECT",
            "SET",
            "TABLE",
            "THEN",
            "UNION",
            "UNIQUE",
            "UPDATE",
            "VALUES",
            "WHEN",
            "WHERE",
            "WITH",
        ),
    ),
)

# Extension -> profile lookup built once at import time.
_BY_EXTENSION: dict[str, LanguageProfile] = {
    ext: profile for profile in _PROFILES for ext in profile.extensions
}

PLAIN_PROFILE: LanguageProfile = LanguageProfile("Plain text", ())


def get_profile_for_path(path: Path | None) -> LanguageProfile:
    """Return the language profile for *path*, or the plain-text profile."""
    if path is None:
        return PLAIN_PROFILE
    return _BY_EXTENSION.get(path.suffix.lower(), PLAIN_PROFILE)


def get_profile_by_name(name: str) -> LanguageProfile | None:
    """Return a profile by display name (case-insensitive), or ``None``."""
    name_lower = name.lower()
    for profile in _PROFILES:
        if profile.name.lower() == name_lower:
            return profile
    return None


def all_profiles() -> list[LanguageProfile]:
    """Return all built-in profiles sorted by name."""
    return sorted(_PROFILES, key=lambda p: p.name)
