"""Static data tables for the settings registry (extracted for GATE-11).

These dataclasses and the ``SETTING_GROUPS`` / ``SETTING_SPECS`` tables were
lifted out of :mod:`quill.core.settings_registry` to keep that module under its
GATE-11 module-size budget. The registry re-exports every name defined here, so
the public import surface is unchanged. No ``wx`` imports; pure data.
"""

from __future__ import annotations

from dataclasses import dataclass

#: Bump when the exported document shape changes in a backward-incompatible way.
SCHEMA_VERSION = 1


@dataclass(frozen=True, slots=True)
class SettingSpec:
    """One tunable setting, mapped to a :class:`Settings` attribute."""

    key: str
    label: str
    group: str
    kind: str  # "bool" | "choice" | "int" | "float" | "text"
    description: str = ""
    choices: tuple[tuple[str, str], ...] = ()  # (stored value, human label)
    minimum: float | None = None
    maximum: float | None = None
    feature_id: str = ""
    keywords: tuple[str, ...] = ()


@dataclass(frozen=True, slots=True)
class SettingGroup:
    """A labelled cluster of settings, surfaced as one tab."""

    id: str
    title: str
    description: str = ""


SETTING_GROUPS: tuple[SettingGroup, ...] = (
    SettingGroup("general", "General", "Appearance, window, and startup behavior."),
    SettingGroup("editing", "Editing", "How the editor behaves while you write."),
    SettingGroup(
        "navigation",
        "Navigation and QUILL Key",
        "Structural movement, browse mode, and the QUILL key.",
    ),
    SettingGroup(
        "accessibility",
        "Accessibility and Announcements",
        "Screen-reader announcements and accessibility behavior.",
    ),
    SettingGroup("read_aloud", "Read Aloud", "Spoken playback engine and voice tuning."),
    SettingGroup("ai", "AI and Assistant", "Writing assistant tone and behavior."),
    SettingGroup(
        "transcription",
        "Transcription",
        "BITS Whisperer speech-model and provider behavior.",
    ),
    SettingGroup(
        "watch",
        "Watch Folders",
        "Default behavior for watched-folder automation.",
    ),
    SettingGroup(
        "integration",
        "Integration and Context Menu",
        "File-manager right-click verbs and how QUILL is offered on files.",
    ),
    SettingGroup("updates", "Updates", "Update checking and release channel."),
    SettingGroup(
        "security",
        "Security and Privacy",
        "Host-key trust, network consent, and other safety toggles.",
    ),
    SettingGroup(
        "developer",
        "Developer Console",
        "Python and TypeScript consoles for developers and power users.",
    ),
)

_GROUP_IDS = {group.id for group in SETTING_GROUPS}


SETTING_SPECS: tuple[SettingSpec, ...] = (
    # --- General -----------------------------------------------------------
    SettingSpec(
        "theme",
        "Theme",
        "general",
        "choice",
        "Overall light or dark appearance.",
        choices=(("system", "System"), ("light", "Light"), ("dark", "Dark")),
        keywords=("dark mode", "light", "appearance", "color"),
    ),
    SettingSpec(
        "title_bar_path_mode",
        "Title bar path",
        "general",
        "choice",
        "Show just the file name or the full path in the title bar.",
        choices=(("name", "File name only"), ("full_path", "Full path")),
        keywords=("title", "path", "filename"),
    ),
    SettingSpec(
        "dirty_title_style",
        "Unsaved-change title style",
        "general",
        "choice",
        "How the title bar marks a document with unsaved changes.",
        choices=(
            ("text", "Text"),
            ("asterisk", "Asterisk"),
            ("asterisk_text", "Asterisk and text"),
        ),
        keywords=("modified", "dirty", "asterisk", "unsaved"),
    ),
    SettingSpec(
        "tray_enabled",
        "Enable system tray mode",
        "general",
        "bool",
        "Keep QUILL available from the system tray.",
        keywords=("tray", "notification area", "minimize"),
    ),
    SettingSpec(
        "show_tab_control",
        "Show tab control",
        "general",
        "bool",
        "Show a tab strip for open documents.",
        keywords=("tabs", "documents"),
    ),
    SettingSpec(
        "start_with_no_document_open",
        "Start with no document open",
        "general",
        "bool",
        "Open to an empty workspace instead of restoring a document.",
        keywords=("startup", "blank", "empty"),
    ),
    SettingSpec(
        "preview_browser",
        "Preview browser",
        "general",
        "text",
        "Which browser opens HTML previews.",
        keywords=("preview", "browser", "html"),
    ),
    SettingSpec(
        "auto_side_preview",
        "Open preview beside the editor",
        "general",
        "bool",
        "Show HTML previews in a side pane instead of a separate window.",
        keywords=("preview", "side", "pane", "html"),
    ),
    SettingSpec(
        "recent_files_limit",
        "Recent files to remember",
        "general",
        "int",
        "How many entries the Recent Files list keeps (1 to 50).",
        minimum=1,
        maximum=50,
        keywords=("recent", "history", "files"),
    ),
    SettingSpec(
        "language",
        "Interface language",
        "general",
        "text",
        "BCP 47 language tag for the UI (e.g. 'en', 'fr', 'es'). "
        "Leave blank to use the operating-system language.",
        keywords=("language", "locale", "translation", "interface"),
    ),
    SettingSpec(
        "confirm_destructive_actions",
        "Confirm destructive actions",
        "general",
        "bool",
        "Ask before actions that discard work, such as clearing or overwriting.",
        keywords=("confirm", "prompt", "destructive", "safety"),
    ),
    SettingSpec(
        "startup_folder",
        "Default file-open folder",
        "general",
        "text",
        "Initial folder for Open and Save As dialogs. Leave blank to use the Documents folder.",
        keywords=("startup folder", "default folder", "open folder", "file dialog", "start folder"),
    ),
    SettingSpec(
        "default_new_document_format",
        "Default new-document format",
        "general",
        "choice",
        "The format a brand-new document starts in.",
        choices=(
            ("markdown", "Markdown"),
            ("text", "Plain text"),
            ("html", "HTML"),
        ),
        keywords=("new document", "format", "default"),
    ),
    SettingSpec(
        "default_export_preset",
        "Default export preset",
        "general",
        "choice",
        "The format pre-selected in the export dialog.",
        choices=(
            ("html", "HTML"),
            ("markdown", "Markdown"),
            ("pdf", "PDF"),
            ("docx", "Word"),
            ("epub", "EPUB"),
            ("text", "Plain text"),
        ),
        keywords=("export", "preset", "default", "format"),
    ),
    # --- Editing -----------------------------------------------------------
    SettingSpec(
        "soft_wrap",
        "Enable soft wrap",
        "editing",
        "bool",
        "Wrap long lines to the window width.",
        keywords=("wrap", "word wrap", "lines"),
    ),
    SettingSpec(
        "wrap_find",
        "Wrap find searches",
        "editing",
        "bool",
        "Continue a search from the top after reaching the end.",
        keywords=("find", "search", "wrap"),
    ),
    SettingSpec(
        "indent_with_tabs",
        "Indent with tabs",
        "editing",
        "bool",
        "Insert tab characters instead of spaces when indenting.",
        keywords=("tab", "indent", "spaces"),
    ),
    SettingSpec(
        "indent_size",
        "Indent size",
        "editing",
        "int",
        "Number of spaces per indent level (1 to 8).",
        minimum=1,
        maximum=8,
        keywords=("indent", "spaces", "width"),
    ),
    SettingSpec(
        "spellcheck_as_you_type",
        "Spell check as you type",
        "editing",
        "bool",
        "Flag misspellings while you write.",
        feature_id="core.spellcheck",
        keywords=("spelling", "spell check", "typos"),
    ),
    SettingSpec(
        "intellisense_as_you_type",
        "Word prediction and tag IntelliSense",
        "editing",
        "bool",
        "Suggest words and tags while you type.",
        feature_id="core.intellisense",
        keywords=("autocomplete", "prediction", "intellisense"),
    ),
    SettingSpec(
        "snippet_trigger_expansion",
        "Expand snippet triggers while typing",
        "editing",
        "bool",
        "Expand a snippet trigger when you type its delimiter.",
        keywords=("snippet", "expand", "template"),
    ),
    SettingSpec(
        "abbreviation_expansion",
        "Abbreviation expansion",
        "editing",
        "bool",
        "Automatically expand abbreviations as you type (e.g. 'btw ' becomes 'by the way ').",
        keywords=("abbreviation", "shorthand", "textexpander", "autocorrect", "expand"),
    ),
    SettingSpec(
        "abbreviation_expansion_sound",
        "Play sound on abbreviation expansion",
        "editing",
        "bool",
        "Play a sound each time an abbreviation is expanded.",
        keywords=("abbreviation", "sound", "audio", "beep"),
    ),
    SettingSpec(
        "abbreviation_expansion_sound_file",
        "Abbreviation expansion sound file",
        "editing",
        "text",
        "Path to a .wav file played on expansion. Leave blank for the default system sound.",
        keywords=("abbreviation", "sound", "wav", "audio"),
    ),
    SettingSpec(
        "persistent_undo",
        "Enable persistent undo",
        "editing",
        "bool",
        "Keep undo history across sessions.",
        keywords=("undo", "history", "persistent"),
    ),
    SettingSpec(
        "markdown_clipboard_format",
        "Markdown clipboard format",
        "editing",
        "choice",
        "Format used when copying Markdown with source.",
        choices=(("html", "HTML"), ("rtf", "Rich text")),
        keywords=("clipboard", "copy", "markdown", "format"),
    ),
    SettingSpec(
        "csv_open_mode",
        "How to open CSV files",
        "editing",
        "choice",
        "Open CSV files as plain text, as a grid, or ask each time.",
        choices=(("prompt", "Ask each time"), ("text", "Plain text"), ("grid", "Grid")),
        keywords=("csv", "open", "grid", "table"),
    ),
    SettingSpec(
        "word_open_mode",
        "How to open Word files",
        "editing",
        "choice",
        "Open Word files as plain text, as structured content, or ask each time.",
        choices=(
            ("prompt", "Ask each time"),
            ("text", "Plain text"),
            ("structured", "Structured"),
        ),
        keywords=("word", "docx", "open", "structured"),
    ),
    # editor_surface spec intentionally omitted while core.rich_text_lens is
    # locked_off — re-add choices=(..., ("rich", "Rich text lens")) when ready.
    SettingSpec(
        "save_as_surface_sync",
        "Reload after Save As to match the format",
        "editing",
        "choice",
        "After Save As changes the file type, optionally reload the file so the "
        "editing surface (Rich text or plain text) matches the new format. "
        "Reloading replaces the editor contents with the saved file.",
        choices=(
            ("prompt", "Ask each time"),
            ("always", "Reload automatically"),
            ("never", "Keep current surface"),
        ),
        keywords=("save as", "convert", "rtf", "reload", "surface", "format"),
    ),
    SettingSpec(
        "plain_text_link_style",
        "Links in plain-text export",
        "editing",
        "choice",
        "How Markdown links are written when you save or export as plain text. "
        "Keeping the URL avoids losing where a link pointed.",
        choices=(
            ("text", "Link text only"),
            ("text_url", "Link text and URL"),
            ("url", "URL only"),
            ("markdown", "Keep Markdown link"),
        ),
        keywords=("link", "url", "plain text", "export", "convert"),
    ),
    SettingSpec(
        "autosave_interval_seconds",
        "Autosave interval (seconds)",
        "editing",
        "int",
        "How often the editor autosaves the open document (5 to 600).",
        minimum=5,
        maximum=600,
        keywords=("autosave", "interval", "timing", "save"),
    ),
    SettingSpec(
        "autoformat_smart_quotes",
        "Autoformat straight quotes to curly",
        "editing",
        "bool",
        "Convert straight quotes to typographic quotes while you type.",
        keywords=("autoformat", "quotes", "typography", "smart quotes"),
    ),
    SettingSpec(
        "autoformat_dashes",
        "Autoformat double hyphen to dash",
        "editing",
        "bool",
        "Convert a double hyphen to an en or em dash while you type.",
        keywords=("autoformat", "dash", "hyphen", "typography"),
    ),
    # --- Navigation and QUILL key -----------------------------------------
    SettingSpec(
        "browse_mode_wrap",
        "Wrap QUILL browse navigation",
        "navigation",
        "bool",
        "Wrap to the other end at document boundaries while browsing.",
        feature_id="core.navigate",
        keywords=("browse", "wrap", "navigation"),
    ),
    SettingSpec(
        "browse_mode_feedback",
        "QUILL browse feedback",
        "navigation",
        "choice",
        "How browse-mode movement is signalled.",
        choices=(
            ("speech", "Speech only"),
            ("sound", "Sound only"),
            ("both", "Speech and sound"),
            ("none", "Silent"),
        ),
        feature_id="core.navigate",
        keywords=("browse", "feedback", "sound", "speech"),
    ),
    SettingSpec(
        "browse_mode_preload_cache",
        "Preload QUILL browse cache in background",
        "navigation",
        "bool",
        "Build the navigation cache ahead of first use.",
        feature_id="core.navigate",
        keywords=("browse", "cache", "preload", "quick nav"),
    ),
    SettingSpec(
        "quill_key_timeout_seconds",
        "QUILL key timeout (seconds)",
        "navigation",
        "float",
        "How long the QUILL key prefix and browse mode wait before expiring. 0 means no timeout.",
        minimum=0.0,
        maximum=60.0,
        keywords=("quill key", "timeout", "prefix"),
    ),
    # --- Accessibility -----------------------------------------------------
    SettingSpec(
        "ocr_engine",
        "OCR engine",
        "accessibility",
        "choice",
        "Which engine recognizes text in images. Automatic uses the built-in Windows engine.",
        choices=(
            ("auto", "Automatic"),
            ("windows", "Windows (built-in)"),
        ),
        feature_id="core.ocr",
        keywords=("ocr", "image", "text", "windows", "recognition"),
    ),
    # --- External file-change watch and safe reload (FEAT-19) --------------
    SettingSpec(
        "external_change_watch_enabled",
        "Watch the open file for external changes",
        "general",
        "bool",
        "Notice when another program changes or deletes the file you are editing "
        "and react safely instead of silently losing or overwriting your work.",
        keywords=("watch", "external", "reload", "file change", "conflict"),
    ),
    SettingSpec(
        "external_change_auto_reload_when_clean",
        "Reload automatically when you have no unsaved edits",
        "general",
        "bool",
        "When the file changes on disk and your buffer is unmodified, reload in "
        "place without moving the cursor. Turn off to be prompted instead.",
        keywords=("reload", "auto", "external", "clean"),
    ),
    SettingSpec(
        "external_change_prompt_on_conflict",
        "Ask before discarding unsaved edits on a conflict",
        "general",
        "bool",
        "When the file changes on disk while you have unsaved edits, offer reload, "
        "keep-mine, or compare. Your text is never overwritten silently.",
        keywords=("conflict", "prompt", "unsaved", "external", "reload"),
    ),
    SettingSpec(
        "external_change_debounce_ms",
        "External-change debounce (milliseconds)",
        "general",
        "int",
        "How long to wait after a change is seen before reacting, so a program "
        "writing a file in several steps is handled once (0 to 10000).",
        minimum=0,
        maximum=10000,
        keywords=("debounce", "external", "timing", "watch"),
    ),
    SettingSpec(
        "quick_nav_debounce_ms",
        "Quick Nav debounce (milliseconds)",
        "navigation",
        "int",
        "How long Quick Nav waits between keystrokes before searching (0 to 2000).",
        minimum=0,
        maximum=2000,
        feature_id="core.navigate",
        keywords=("quick nav", "debounce", "timing"),
    ),
    SettingSpec(
        "quick_nav_min_chars",
        "Quick Nav minimum characters",
        "navigation",
        "int",
        "How many characters Quick Nav needs before it starts matching (1 to 5).",
        minimum=1,
        maximum=5,
        feature_id="core.navigate",
        keywords=("quick nav", "threshold", "characters"),
    ),
    SettingSpec(
        "browse_mode_sticky",
        "Sticky browse mode",
        "navigation",
        "bool",
        "Keep browse mode active after moving instead of returning to editing.",
        feature_id="core.navigate",
        keywords=("browse", "sticky", "navigation"),
    ),
    SettingSpec(
        "quill_key_sound_enter",
        "Custom sound for browse mode entry (WAV file)",
        "navigation",
        "text",
        "WAV file played when entering QUILL browse mode. Blank for default beep.",
        keywords=("quill key", "sound", "earcon", "browse", "enter"),
    ),
    SettingSpec(
        "quill_key_sound_exit",
        "Custom sound for browse mode exit (WAV file)",
        "navigation",
        "text",
        "WAV file played when exiting QUILL browse mode. Blank for default beep.",
        keywords=("quill key", "sound", "earcon", "browse", "exit"),
    ),
    SettingSpec(
        "quill_key_sound_move",
        "Custom sound for browse navigation (WAV file)",
        "navigation",
        "text",
        "WAV file played on each QUILL browse move. Blank for default beep.",
        keywords=("quill key", "sound", "earcon", "browse", "move"),
    ),
    SettingSpec(
        "quill_key_sound_error",
        "Custom sound for browse not-found (WAV file)",
        "navigation",
        "text",
        "WAV file played when a QUILL browse target is not found. Blank for beep.",
        keywords=("quill key", "sound", "earcon", "browse", "error"),
    ),
    SettingSpec(
        "quick_nav_include_headings",
        "Include headings in Quick Nav",
        "navigation",
        "bool",
        "Offer headings as Quick Nav targets.",
        feature_id="core.navigate",
        keywords=("quick nav", "headings", "elements"),
    ),
    SettingSpec(
        "quick_nav_include_links",
        "Include links in Quick Nav",
        "navigation",
        "bool",
        "Offer links as Quick Nav targets.",
        feature_id="core.navigate",
        keywords=("quick nav", "links", "elements"),
    ),
    SettingSpec(
        "quick_nav_include_lists",
        "Include lists in Quick Nav",
        "navigation",
        "bool",
        "Offer lists as Quick Nav targets.",
        feature_id="core.navigate",
        keywords=("quick nav", "lists", "elements"),
    ),
    # --- Accessibility -----------------------------------------------------
    SettingSpec(
        "announcement_backend",
        "Announcement backend",
        "accessibility",
        "choice",
        "How spoken status announcements are delivered.",
        choices=(
            ("auto", "Automatic"),
            ("prism", "PRISM bridge"),
            ("status_only", "Status bar only"),
        ),
        feature_id="core.accessibility",
        keywords=("announcement", "screen reader", "speech"),
    ),
    SettingSpec(
        "announcement_trace_enabled",
        "Record announcement trace",
        "accessibility",
        "bool",
        "Log announcements for diagnostics (no document content is captured).",
        feature_id="core.accessibility",
        keywords=("trace", "diagnostics", "announcement"),
    ),
    # --- Read Aloud --------------------------------------------------------
    SettingSpec(
        "announcement_verbosity",
        "Announcement verbosity",
        "accessibility",
        "choice",
        "Overall chattiness of spoken status announcements.",
        choices=(
            ("minimal", "Minimal"),
            ("normal", "Normal"),
            ("verbose", "Verbose"),
        ),
        feature_id="core.accessibility",
        keywords=("verbosity", "announcements", "chatty", "speech"),
    ),
    SettingSpec(
        "announce_wrap",
        "Announce search and navigation wrap",
        "accessibility",
        "bool",
        "Speak a notice when a search or navigation wraps around.",
        feature_id="core.accessibility",
        keywords=("announce", "wrap", "navigation"),
    ),
    SettingSpec(
        "announce_counts",
        "Announce word and character counts",
        "accessibility",
        "bool",
        "Speak word and character counts when they are requested.",
        feature_id="core.accessibility",
        keywords=("announce", "counts", "words"),
    ),
    SettingSpec(
        "announce_mode_changes",
        "Announce mode entry and expiry",
        "accessibility",
        "bool",
        "Speak when a mode such as browse or the QUILL key is entered or expires.",
        feature_id="core.accessibility",
        keywords=("announce", "mode", "browse", "quill key"),
    ),
    SettingSpec(
        "announce_spelling",
        "Announce spelling results",
        "accessibility",
        "bool",
        "Speak spelling feedback such as misspelling counts.",
        feature_id="core.accessibility",
        keywords=("announce", "spelling", "spell check"),
    ),
    SettingSpec(
        "announce_punctuation_level",
        "Spoken punctuation level",
        "accessibility",
        "choice",
        "How much punctuation announcements include.",
        choices=(
            ("none", "None"),
            ("some", "Some"),
            ("most", "Most"),
            ("all", "All"),
        ),
        feature_id="core.accessibility",
        keywords=("punctuation", "announce", "speech"),
    ),
    SettingSpec(
        "announcement_throttle_ms",
        "Announcement throttle (milliseconds)",
        "accessibility",
        "int",
        "Minimum gap between spoken announcements; 0 means no throttle (0 to 2000).",
        minimum=0,
        maximum=2000,
        feature_id="core.accessibility",
        keywords=("throttle", "announcements", "timing"),
    ),
    # --- Read Aloud --------------------------------------------------------
    SettingSpec(
        "read_aloud_engine",
        "Read Aloud engine",
        "read_aloud",
        "choice",
        "Speech engine used for read aloud.",
        choices=(
            ("pyttsx3", "System (pyttsx3)"),
            ("dectalk", "DECtalk"),
            ("piper", "Piper"),
            ("kokoro", "Kokoro"),
            ("espeak", "eSpeak"),
            ("openvoice", "OpenVoice"),
        ),
        feature_id="core.read_aloud",
        keywords=("read aloud", "tts", "voice", "engine"),
    ),
    SettingSpec(
        "read_aloud_rate",
        "Read Aloud rate",
        "read_aloud",
        "int",
        "Words per minute for the system engine (80 to 450).",
        minimum=80,
        maximum=450,
        feature_id="core.read_aloud",
        keywords=("read aloud", "rate", "speed"),
    ),
    SettingSpec(
        "read_aloud_volume",
        "Read Aloud volume",
        "read_aloud",
        "int",
        "Playback volume percentage (0 to 100).",
        minimum=0,
        maximum=100,
        feature_id="core.read_aloud",
        keywords=("read aloud", "volume"),
    ),
    SettingSpec(
        "read_aloud_pitch",
        "Read Aloud pitch",
        "read_aloud",
        "int",
        "Voice pitch (0 to 100).",
        minimum=0,
        maximum=100,
        feature_id="core.read_aloud",
        keywords=("read aloud", "pitch"),
    ),
    SettingSpec(
        "read_aloud_sentence_pause_ms",
        "Read Aloud sentence pause (milliseconds)",
        "read_aloud",
        "int",
        "Extra pause inserted between sentences during read aloud (0 to 2000).",
        minimum=0,
        maximum=2000,
        feature_id="core.read_aloud",
        keywords=("read aloud", "pause", "pacing", "timing"),
    ),
    # --- AI and assistant --------------------------------------------------
    SettingSpec(
        "assistant_enabled",
        "Enable writing assistant",
        "ai",
        "bool",
        "Turn the local writing assistant on.",
        feature_id="future.ai",
        keywords=("assistant", "ai", "writing"),
    ),
    SettingSpec(
        "assistant_prompt_style",
        "Assistant prompt style",
        "ai",
        "choice",
        "The tone the assistant uses.",
        choices=(
            ("balanced", "Balanced"),
            ("concise", "Concise"),
            ("gentle", "Gentle"),
            ("technical", "Technical"),
        ),
        feature_id="future.ai",
        keywords=("assistant", "tone", "style", "prompt"),
    ),
    SettingSpec(
        "ai_chat_default_provider",
        "Ask AI default provider",
        "ai",
        "text",
        "Default provider selected when the Ask AI dialog opens"
        " (ollama, ollama_cloud, openai, claude, openrouter, gemini, custom).",
        keywords=("ai", "chat", "provider", "ollama", "openai", "claude", "openrouter", "gemini"),
    ),
    SettingSpec(
        "ai_chat_default_model",
        "Ask AI default model",
        "ai",
        "text",
        "Default model ID selected when the Ask AI dialog opens."
        " Leave blank to use the first model in the list.",
        keywords=("ai", "chat", "model"),
    ),
    SettingSpec(
        "ollama_base_url",
        "Ollama base URL",
        "ai",
        "text",
        "Base URL for the Ollama server. Default: http://localhost:11434",
        keywords=("ollama", "ai", "local", "url"),
    ),
    SettingSpec(
        "ai_prompt_default_model",
        "AI prompt default model",
        "ai",
        "text",
        "Default model ID used when running prompt-library prompts."
        " Leave blank to fall back to the Ask AI default model.",
        keywords=("ai", "prompt", "model", "prompt library", "grammar"),
    ),
    # --- Bug reporting --------------------------------------------------------
    SettingSpec(
        "bug_reporter_name",
        "Bug reporter name",
        "general",
        "text",
        "Your name, pre-filled in the Report a Bug dialog for convenience.",
        keywords=("name", "bug", "report", "contact"),
    ),
    SettingSpec(
        "bug_reporter_email",
        "Bug reporter email",
        "general",
        "text",
        "Your contact email, pre-filled in the Report a Bug dialog for convenience.",
        keywords=("email", "bug", "report", "contact"),
    ),
    # --- Transcription -----------------------------------------------------
    SettingSpec(
        "bw_provider_mode",
        "Transcription provider preference",
        "transcription",
        "choice",
        "Prefer on-device or cloud transcription providers.",
        choices=(("local_first", "Local first"), ("cloud_first", "Cloud first")),
        feature_id="core.bw_providers",
        keywords=("transcription", "whisper", "provider", "cloud", "local"),
    ),
    SettingSpec(
        "bw_show_cloud_providers",
        "Show cloud transcription providers",
        "transcription",
        "bool",
        "List cloud providers alongside on-device ones.",
        feature_id="core.bw_providers",
        keywords=("transcription", "cloud", "providers"),
    ),
    SettingSpec(
        "bw_auto_open_status_page_on_download_start",
        "Auto-open Status Page on model download",
        "transcription",
        "bool",
        "Open the Status Page when a speech-model download starts.",
        feature_id="core.bw_transcription",
        keywords=("transcription", "status page", "download"),
    ),
    SettingSpec(
        "status_page_refresh_announcement_cadence",
        "Status page refresh announcements",
        "transcription",
        "choice",
        "How often the Status Page speaks refresh updates.",
        choices=(
            ("quiet", "Quiet"),
            ("normal", "Normal"),
            ("verbose", "Verbose"),
        ),
        feature_id="core.bw_transcription",
        keywords=("status page", "announcements", "cadence"),
    ),
    SettingSpec(
        "bw_safe_mode_lock",
        "BITS Whisperer safe mode lock",
        "transcription",
        "bool",
        "Block download and retry actions while keeping status surfaces.",
        feature_id="core.bw_transcription",
        keywords=("transcription", "safe mode", "lock"),
    ),
    SettingSpec(
        "voice_commands_enabled",
        "Hey QUILL voice commands",
        "transcription",
        "bool",
        "Enable Hey QUILL voice commands during dictation (e.g., 'Hey QUILL save file').",
        feature_id="core.voice_commands",
        keywords=("voice commands", "hey quill", "dictation", "speech"),
    ),
    # --- Watch Folders -----------------------------------------------------
    SettingSpec(
        "watch_folder_enabled",
        "Enable folder watching by default",
        "watch",
        "bool",
        "Turn watched-folder automation on when QUILL starts.",
        feature_id="core.watch",
        keywords=("watch", "folder", "automation", "monitor"),
    ),
    SettingSpec(
        "watch_folder_path",
        "Default watch folder",
        "watch",
        "text",
        "Folder to watch for new files when watching is enabled.",
        feature_id="core.watch",
        keywords=("watch", "folder", "path", "directory"),
    ),
    SettingSpec(
        "watch_folder_include_subfolders",
        "Include subfolders",
        "watch",
        "bool",
        "Also watch files inside nested subfolders.",
        feature_id="core.watch",
        keywords=("watch", "subfolders", "recursive"),
    ),
    SettingSpec(
        "watch_folder_process_existing",
        "Process existing files on start",
        "watch",
        "bool",
        "Run actions against files already present when watching begins.",
        feature_id="core.watch",
        keywords=("watch", "existing", "backlog"),
    ),
    SettingSpec(
        "watch_folder_auto_start",
        "Start watching automatically",
        "watch",
        "bool",
        "Begin watching the default folder as soon as QUILL launches.",
        feature_id="core.watch",
        keywords=("watch", "auto start", "startup"),
    ),
    SettingSpec(
        "watch_folder_poll_interval_seconds",
        "Poll interval (seconds)",
        "watch",
        "int",
        "How often the watched folder is checked for changes (2 to 300).",
        feature_id="core.watch",
        minimum=2,
        maximum=300,
        keywords=("watch", "poll", "interval", "seconds"),
    ),
    # --- Updates -----------------------------------------------------------
    SettingSpec(
        "auto_check_updates",
        "Check for updates on startup",
        "updates",
        "bool",
        "Look for a newer release each time QUILL starts.",
        feature_id="core.updates",
        keywords=("updates", "startup", "check"),
    ),
    SettingSpec(
        "beta_updates",
        "Get beta updates",
        "updates",
        "bool",
        "Receive pre-release builds, which may be unstable.",
        feature_id="core.updates",
        keywords=("updates", "beta", "channel", "prerelease"),
    ),
    # --- Integration and Context Menu --------------------------------------
    SettingSpec(
        "shell_integration_enabled",
        "Show QUILL in the file-manager right-click menu",
        "integration",
        "bool",
        "Add QUILL's enabled verbs to the file manager context menu.",
        keywords=("context menu", "right click", "explorer", "send to", "shell"),
    ),
    SettingSpec(
        "shell_file_types",
        "File types offered to QUILL",
        "integration",
        "choice",
        "Which kinds of files show QUILL verbs in the context menu.",
        choices=(
            ("images", "Images only"),
            ("images_pdf", "Images and PDF"),
            ("images_pdf_docs", "Images, PDF, and text documents"),
        ),
        keywords=("file types", "images", "pdf", "documents"),
    ),
    SettingSpec(
        "shell_verb_open",
        "Offer \u201cOpen in QUILL\u201d",
        "integration",
        "bool",
        "Add an \u201cOpen in QUILL\u201d verb for supported text documents.",
        keywords=("open", "context menu", "verb"),
    ),
    SettingSpec(
        "shell_verb_ocr",
        "Offer \u201cOCR with QUILL\u201d",
        "integration",
        "bool",
        "Add an OCR-to-text verb for images and PDF files.",
        feature_id="core.ocr",
        keywords=("ocr", "image", "pdf", "context menu", "verb"),
    ),
    SettingSpec(
        "shell_verb_ocr_structured",
        "Offer \u201cOCR with QUILL (structured Markdown)\u201d",
        "integration",
        "bool",
        "Add an AI-assisted OCR verb that returns structured Markdown.",
        feature_id="core.ocr",
        keywords=("ocr", "markdown", "structured", "ai", "context menu"),
    ),
    SettingSpec(
        "shell_verb_read",
        "Offer \u201cRead aloud in QUILL\u201d",
        "integration",
        "bool",
        "Add a verb that opens a file and starts reading it aloud.",
        feature_id="read_aloud",
        keywords=("read aloud", "speech", "context menu", "verb"),
    ),
    # --- Multi-press -------------------------------------------------------
    SettingSpec(
        "multi_press_window_ms",
        "Multi-press time window (ms)",
        "editing",
        "int",
        "How long QUILL waits for a second or third keypress before treating "
        "the first as a single press. Applies to Copy Tray and Command Palette "
        "multi-press actions. 300 ms suits fast typists; 500 ms helps users "
        "with motor control differences. Default: 400.",
        keywords=("multi press", "double press", "copy tray", "keyboard", "timer"),
    ),
    # --- Security and privacy ----------------------------------------------
    # --- Developer Console -------------------------------------------------
    SettingSpec(
        "console_enabled",
        "Enable Developer Console",
        "developer",
        "bool",
        "When on, the Python and TypeScript developer consoles are available "
        "under Tools > Advanced > Developer Console. Off by default for "
        "Essential and Writer profiles.",
        keywords=("developer console", "qdc", "scripting", "python", "automation"),
        feature_id="core.developer_console",
    ),
    SettingSpec(
        "console_python_timeout",
        "Python console execution timeout (seconds)",
        "developer",
        "int",
        "Maximum seconds a Python console command may run before QUILL interrupts it. Default: 30.",
        minimum=5,
        maximum=300,
        keywords=("developer console", "python", "timeout"),
        feature_id="core.developer_console",
    ),
    SettingSpec(
        "console_typescript_timeout",
        "TypeScript console execution timeout (seconds)",
        "developer",
        "int",
        "Maximum seconds a TypeScript console command may run before the "
        "Node worker is restarted. Default: 30.",
        minimum=5,
        maximum=300,
        keywords=("developer console", "typescript", "node", "timeout"),
        feature_id="core.developer_console.typescript",
    ),
    SettingSpec(
        "ssh_trust_first_use",
        "Trust SSH hosts on first connection",
        "security",
        "bool",
        "When on, QUILL remembers a host key the first time it is seen "
        "(paramiko AutoAddPolicy). When off, the safer default, an "
        "unknown host key rejects the connection so you notice the "
        "mismatch. Off unless you have a specific reason to change it.",
        keywords=("ssh", "host key", "trust", "paramiko", "security"),
    ),
)
